Feature/change structor
EntryDSM-Internship/team_1_frontend pull request #1
Opened 2019-12-04 14:03 UTC by sema0710

너무 늦게 pr을 날려서 commit이 쌓인점에 대해서 사죄드립니다..

2019-12-04 14:28 UTC, soheejang15 commented
PR 날릴 때 reviewer에 2학년 프론트분들 추가해주세요 🙂
commit이 많이 쌓여도 나눠서 PR을 날릴 수 있는 경우에는 나눠주시면 좋아요!

2019-12-04 14:36 UTC, soheejang15 commented on src/App.js
> +        <Route path="/Main" component={TimeLine}/>
나머지 부분에는 exact를 뺀 이유가 있나요?

2019-12-04 14:36 UTC, junu126 requested changes

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/header/TimeLineHeaderButtons.js
> +                <TimeLineHeaderButton alt="" src={search}>
alt 넣어줘욘

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/post/Post.js
> +            <PostMain></PostMain>
<PostMain /> 이런식으로 닫아주세요

2019-12-04 14:36 UTC, junu126 commented on src/App.js
>        <Router>
react-router-dom을 공부해 보고

`Switch`의 필요성에 생각해보세요

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/post/PostMain.js
> +                    <TimeLinePostUserImg alt="" src="https://pbs.twimg.com/profile_images/446356636710363136/OYIaJ1KK.png"/>
정적인 이미지 링크는 넣지 않는게 좋을 것 같습니다.
혹시 더미데이터면 상관없지만 필요한 데이터면 따로 다운받으세요

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/writing/TimeLineWriteImg.js
> +    props.del("");
props를 구조분해할당 하지 않은 이유가 무엇인가요?? 가독성이 불편한 것 같아서요

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/writing/TimeLineWriteImg.js
> +    props.del("");
그리고 `props.del("");`이 뭐하는 함수인지는 모르겠지만 저렇게 사용하게 되면 컴포넌트가 rendering될 때마다 실행되서 비 효율적입니다.

`useEffect`를 이용해보세요

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/writing/Write.js
> +    const [on,ChangeOn] = useState(false);
boolean의 변수명은 명사로 적는게 좋습니다.

EX)

`const [isAccept, setIsAccept] = useState(false);`

2019-12-04 14:36 UTC, junu126 commented on src/components/Main/writing/WriteImgButton.js
> +            let reader = new FileReader();
이미지를 다루는 부분에서 많이 힘들어 하는 것을 보았는데 `FileReader`를 사용하는 방법 말고 좋은 방법을 소개시켜드리겠습니다.

`url.createobjecturl()`이라는 함수가 있는데 인자로 blob 이미지 값을 넘기면 자동으로 이미지를 URL로 바꿔줍니다. 지우는 것도 간단하게 2줄로 구현 할 수 있어요. 한번 검색하고 공부 ㄱㄱ

2019-12-04 14:36 UTC, junu126 commented on src/components/findPassword/page/FindPasswordEmail.js
> +                alert("없는 이메일 입니다");
alert는 브라우저의 동작을 모두 정지시킵니다. popup창을 만들어서 띄워주세요

2019-12-04 14:37 UTC, sema0710 commented on src/App.js
> +        <Route path="/Main" component={TimeLine}/>
아마도 실수인 것 같습니다 수정하겠습니다!

2019-12-04 14:38 UTC, sema0710 commented on src/components/Main/header/TimeLineHeaderButtons.js
> +                <TimeLineHeaderButton alt="" src={search}>
네넵

2019-12-04 14:38 UTC, sema0710 commented on src/components/Main/writing/WriteImgButton.js
> +            let reader = new FileReader();
네 알겠습니다!

2019-12-04 14:39 UTC, sema0710 commented on src/components/Main/writing/Write.js
> +    const [on,ChangeOn] = useState(false);
변수명 짓는게 애매해서 그랬네요
수정하겠습니다

2019-12-04 14:39 UTC, sema0710 commented on src/components/Main/post/PostMain.js
> +                    <TimeLinePostUserImg alt="" src="https://pbs.twimg.com/profile_images/446356636710363136/OYIaJ1KK.png"/>
잠시 대용으로 넣어놓은 더미 데이터 입니다.
곧 서버연동하면서 사라질 예정입니다.

2019-12-04 14:43 UTC, soheejang15 commented on src/components/Main/header/TimeLineHeaderButtons.js
> +import { TimeLineHeaderButtonDiv, TimeLineHeaderButton, TimeLineHeaderButtonImg } from '../../../style/TimeLineStyle'
혹시나 import할 것들이 너무 많아지면 ```import * as 어쩌구 from "./style";```로 불러와서 ```<어쩌구.TimeLineHeaderButtonDiv/>```으로도 사용할 수 있을 것 같아요

2019-12-04 14:44 UTC, soheejang15 commented on src/components/Main/post/Post.js
> +            <PostMain></PostMain>
@junu126 이런식이 뭔가용  ```<PostMain />```으로 작성하면 좋아요

2019-12-04 14:49 UTC, junu126 commented on src/components/Main/post/Post.js
> +            <PostMain></PostMain>
저거 말한거에요

2019-12-09 10:54 UTC, junu126 requested changes

2019-12-09 10:54 UTC, junu126 commented on src/components/Main/writing/WriteImgButton.js
> +        let files = e.target.files;
`let` -> `const` 모두 동일

2019-12-09 10:54 UTC, junu126 commented on src/components/SignUp/SignUpEmailCheckInput.js
> +            <style.EmailInput  minLength="12" maxLength="30" placeholder={props.placeholder} onFocus={inputFocus} onBlur={outFocus}/>
focus가 단지 style을 처리하기 위함이면 styled-components에서 props로 받아서 손 쉽게 해결할 수 있습니다.

2019-12-09 10:55 UTC, junu126 requested changes
+ 리뷰어 코멘트에 답글 달아주세요
(모든 리뷰어의 코멘트에 해당)

2019-12-09 13:40 UTC, sema0710 reviewed
> * 리뷰어 코멘트에 답글 달아주세요
>   (모든 리뷰어의 코멘트에 해당)
네 알겠습니다!

2019-12-09 13:40 UTC, sema0710 commented on src/components/findPassword/page/FindPasswordEmail.js
> +                alert("없는 이메일 입니다");
확인했습니다!

2019-12-09 13:40 UTC, sema0710 commented on src/App.js
> +        <Route path="/Main" component={TimeLine}/>
> 나머지 부분에는 exact를 뺀 이유가 있나요?

실수인 것 같습니다. 
혹시 404 페이지를 만드는게 좋을까요?

2019-12-09 13:40 UTC, sema0710 commented on src/components/Main/writing/TimeLineWriteImg.js
> +    props.del("");
> 그리고 `props.del("");`이 뭐하는 함수인지는 모르겠지만 저렇게 사용하게 되면 컴포넌트가 rendering될 때마다 실행되서 비 효율적입니다.
> 
> `useEffect`를 이용해보세요

img가 delete되는 index가 계속 유지되는 현상을 방지하기 위한 부분이였습니다.
알려주신 방법 적용하면서 없애도록 하겠습니다.

2019-12-09 13:40 UTC, sema0710 commented on src/components/Main/writing/TimeLineWriteImg.js
> +    props.del("");
> props를 구조분해할당 하지 않은 이유가 무엇인가요?? 가독성이 불편한 것 같아서요

습관이 되서 그런거 같습니다.
구조분해할당 하도록 하겠습니다.

2019-12-09 13:40 UTC, sema0710 commented on src/components/Main/post/Post.js
> +            <PostMain></PostMain>
아 넵 확인했습니다!

2019-12-09 13:40 UTC, sema0710 commented on src/components/Main/header/TimeLineHeaderButtons.js
> +import { TimeLineHeaderButtonDiv, TimeLineHeaderButton, TimeLineHeaderButtonImg } from '../../../style/TimeLineStyle'
적용했습니다!

2019-12-09 13:40 UTC, sema0710 commented on src/components/Main/writing/WriteImgButton.js
> +        let files = e.target.files;
적용했습니다!

2019-12-09 13:40 UTC, sema0710 commented on src/components/SignUp/SignUpEmailCheckInput.js
> +            <style.EmailInput  minLength="12" maxLength="30" placeholder={props.placeholder} onFocus={inputFocus} onBlur={outFocus}/>
아 ref로 처리한 줄 알고 계속 안바꿨네요. 수정하겠습니다.

2019-12-12 13:36 UTC, junu126 commented on src/App.js
> +        <Route path="/Main" component={TimeLine}/>
넹

2019-12-12 13:43 UTC, junu126 approved these changes

2019-12-13 03:25 UTC, merged