Feature/set page
EntryDSM-Internship/team_1_frontend pull request #8
Opened 2019-12-31 00:20 UTC by sema0710

서버통신 관련된 부분이 많습니다
로직 부분에 오류가 있는지 확인해주세요

2020-01-03 14:55 UTC, junu126 requested changes

2020-01-03 14:55 UTC, junu126 commented on src/components/FollowerView/FollowerViewContent.js
> +                    <style.FollowerViewImg alt="유저 이미지" src={`http://10.156.147.200:3000${userImg ? userImg : "/profile/0.jpg"}`}/>
테스트 겠죠? src

2020-01-03 14:55 UTC, junu126 commented on src/components/Main/header/FollowRequest/FollowRequest.js
> +                "x-access-token" : access_token,
`access_token`을 `x-access-token`으로 보내는 이유가 있을까요? 서버 파트를 맡은 팀원의 의견을 참고해서 comment 남겨주세요

2020-01-03 14:55 UTC, junu126 commented on src/components/Main/header/FollowRequest/FollowRequest.js
> +    const setContent = (data)=>{
어떤 함수인지는 모르겠는데 `buffer`를 만들어서 component를 담아 두는 방법을 사용한 이유가 있을까요?

2020-01-03 14:55 UTC, junu126 commented on src/components/Main/header/FollowRequest/content/FollowRequestContent.js
> +                <style.FollowRequestContentImg src={`http://10.156.147.200:3000/${userImg}`}/>
src에 `url`을 넣게 되면 이와 같은 상황이 발생할 때마다 url을 적어주게 됩니다. 이런 과정에서 user problem이 발생하고, 이로 인해 유지보수가 힘들어 집니다. url과 같은 정적 데이터는 함수로 빼거나 파일로 분리시켜주세요.

또한 해당 api는 유저의 이미지를 얻어오기 위해 사용되는 것 같습니다. 서버 호출 함수로 따로 빼는 것이 맞다고 생가합니다.

2020-01-03 14:55 UTC, junu126 commented on src/components/Main/post/PostMain.js
> +    let PostImg = contentImg.map((i)=>{
컴폰넌트 내부에서 생성한 변수는 rendering 될 때마다 생성됩니다. 현재 `PostImg`는  state가 변경될 때 마다 배열에 컴포넌트를 저장 하고 있습니다. 많은 트래픽이 발생할 것 입니다.

2020-01-03 14:55 UTC, junu126 commented on src/components/Main/writing/Write.js
> +        axios.post("http://10.156.147.200:3000/api/post/write",
`formdata`를 사용할 때에는 content-type에multipart/form-data를 명시해주어야 합니다.

2020-01-03 14:55 UTC, junu126 commented on src/components/mypage/profile/MypageFollowInfo.js
> +        <style.MypageInfoFollow onClick={()=>{window.location.href="/follow"}}>
이와 같은 `WINDOW`객체 사용은 SPA환경을 무용지물로 만들어버립니다. `react-router-dom`을 활용해보세요

2020-01-04 01:06 UTC, sema0710 commented on src/components/FollowerView/FollowerViewContent.js
> +                    <style.FollowerViewImg alt="유저 이미지" src={`http://10.156.147.200:3000${userImg ? userImg : "/profile/0.jpg"}`}/>
서버쪽에서 img가 없으면 null을 반환해서 저렇게 했습니다.
서버쪽을 고쳐야 할까요?

2025-10-22 06:16 UTC, closed without merging